[package]
edition = "2021"
name = "glytex"
version = "0.2.12"

[dependencies]
anyhow = "*"
clap = { version = "4.5.0", features = ["derive"] }
minotari_app_grpc = { git = "http://github.com/tari-project/tari", tag = "v1.11.0-pre.0" }
num-format = "0.4.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
sha3 = "0.10"
tari_common = { git = "http://github.com/tari-project/tari", tag = "v1.11.0-pre.0" }
tari_common_types = { git = "http://github.com/tari-project/tari", tag = "v1.11.0-pre.0" }
tari_core = { git = "https://github.com/tari-project/tari", tag = "v1.11.0-pre.0", default-features = false, features = [
  "transactions",
] }
tari_crypto = { version = "0.21", features = ["borsh"] }
tari_key_manager = { git = "http://github.com/tari-project/tari", tag = "v1.11.0-pre.0" }
tari_script = { git = "http://github.com/tari-project/tari", tag = "v1.11.0-pre.0" }
tari_shutdown = { git = "https://github.com/tari-project/tari.git", tag = "v1.11.0-pre.0" }
tari_utilities = "0.8"

libsqlite3-sys = { version = "0.25.1", features = ["bundled"] }
prost = "0.13.3"
prost-types = "0.13.3"
rand = "0.8"
tokio = { version = "1.36", features = ["full"] }
tonic = { version = "0.12.3" }

axum = "0.7.5"
cust = { version = "0.3.2", optional = true }
log = "0.4.22"
log4rs = "1.3.0"
opencl-sys = "*"
opencl3 = { version = "0.9.5", optional = true }
thiserror = "1.0.63"

[features]
default = []
nvidia = ["cust"]
